services:
  hydrological_forecasting_ml_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # ports:
    #   - "8787:8787"
    volumes:
      - /home/daniele/documents/gitlab/albertodeluca/alperia-hydrological_forecasting-ml-service/:/home/ml/