FROM ubuntu:latest

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install pytz pandas matplotlib scikit-learn statsmodels numpy

WORKDIR /home/ml/

ENTRYPOINT [ "/bin/python3" ]
CMD [ "/home/ml/src/main/python/bin/ml_process.py", "/home/ml/", "/home/ml/etc/conf/main.json" ]